# Generated by Django 3.1.1 on 2020-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=30)),
                ('series_passport', models.CharField(max_length=15)),
                ('birthday', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('issue_date_passport', models.DateField()),
                ('issue_by_passport', models.CharField(max_length=100)),
                ('passport', models.ImageField(default=None, null=True, upload_to='')),
                ('department_code', models.IntegerField()),
                ('reg_address', models.CharField(max_length=100)),
                ('accept_rules', models.BooleanField(default=False)),
                ('type_qualification', models.IntegerField(choices=[(-1, 'Без квалификации'), (1, 'Высшее экономическое образование в ВУЗе с правом аттестации профучастника'), (2, 'Общая стоимость ценный бумаг и производственных > 6 млн Р. '), (3, 'Опыт работы в финансовой компании > 2 лет'), (4, 'Депозитные, металические счета > 6 млн Р'), (5, 'Активная торговля ценными бумагами и производственными на сумму > 6 млн Р'), (6, 'Уже квалифицирован инвестиционной платформой')], default=None, null=True)),
                ('document_qualification', models.ImageField(default=None, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
    ]
